// Generated by https://quicktype.io

export interface Room {
    id:               number;
    roomNumber:       string;
    roomSpecialityId: number;
    doctorId:         number;
    doctorName?:         number;
}
