// Generated by https://quicktype.io

export interface UserData {
    username:    string;
    email:       string;
    fullName:    string;
    phoneNumber: string;
    gender: string;
    age: string;
    dateCreated: string;
}
