import {
  cilBed,
  cilSpeedometer,
  cilMenu,
  cilBell,
  cilList,
  cilEnvelopeOpen,
  cilTask,
  cilLockLocked,
  cilUser,
  cilPlus,
  cilArrowBottom,
  cilArrowTop,
  cilEnvelopeClosed,
  cilPeople,
  cilPhone,
  cilLayers,
  cilTrash,
  cilLibrary,
  cilGroup,
  cilHospital,
  cilCalendar,
  cilViewColumn,
  cilDoor,
  cilDrinkAlcohol
} from '@coreui/icons';

export const iconSubset = {
  cilBed,
  cilSpeedometer,
  cilMenu,
  cilBell,
  cilList,
  cilEnvelopeOpen,
  cilTask,
  cilLockLocked,
  cilUser,
  cilPlus,
  cilArrowBottom,
  cilArrowTop,
  cilEnvelopeClosed,
  cilPeople,
  cilPhone,
  cilLayers,
  cilTrash,
  cilLibrary,
  cilGroup,
  cilHospital,
  cilCalendar,
  cilViewColumn,
  cilDoor,
  cilDrinkAlcohol
};

export enum IconSubset {
  cilBed = 'cilBed',
  cilSpeedometer = 'cilSpeedometer',
  cilMenu = 'cilMenu',
  cilBell = 'cilBell',
  cilList = 'cilList',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilTask = 'cilTask',
  cilLockLocked = 'cilLockLocked',
  cilUser = 'cilUser',
  cilPlus = 'cilPlus',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowTop = 'cilArrowTop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilPeople = 'cilPeople',
  cilPhone = 'cilPhone',
  cilLayers = 'cilLayers',
  cilTrash = 'cilTrash',
  cilLibrary = 'cilLibrary',
  cilGroup = 'cilGroup',
  cilHospital = 'cilHospital',
  cilCalendar = 'cilCalendar',
  cilViewColumn = 'cilViewColumn',
  cilDoor = 'cilDoor',
  cilDrinkAlcohol = 'cilDrinkAlcohol'
}
